[package]
name = "cs173-autograder-postprocessing"
version = "0.1.0"
authors = ["John Wrenn <john_wrenn@brown.edu>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
streaming-stats = "0.1"
itertools = "0.7.8"
csv = "1.0"